bt_compact.c:264:9: error: comparison of array 'addr' not equal to a null pointer is always true [-Werror,-Wtautological-pointer-compare]
We don't need to test for a valid address, "is a leaf page" is enough.