Revert "generation.c:160:28: error: variable 'start' may be uninitialized when used here"
This reverts commit 8c1e511828ca10cf3fd5cf47aa6d51c9068c9e30.