WT-6248 add HS records to page dumps (#5679)
* replace mention of "las" with "history store"

* When dumping pages, output any history store records for the dumped keys.

Don't dump time windows if they're empty.

Combine the disk and in-memory dump formats to a single format, in the history-store world, we
always want to know the timestamp information from the on-disk format.

* Now that "wt verify -d dump_pages" will display HS records, there's no need for a separate
"dump_history" mechanism.

* Fix debug display of the HS cursor when pointing to a modify record: we don't need to allocate
a WT_UPDATE structure, just convert the underlying function to take a data pointer. This fixes
a typing problem in the call to allocate the WT_UPDATE structure:

bt_debug.c:437:54: error: implicit conversion loses integer precision: 'uint64_t' (aka 'unsigned
long') to 'u_int' (aka 'unsigned int') [-Werror,-Wshorten-64-to-32]