WT-4482 lint (#4407)
* src/os_common/os_fhandle.c:222:39: error: implicit conversion changes
signedness: 'WT_FS_OPEN_FILE_TYPE' to 'int' [-Werror,-Wsign-conversion]

src/os_common/os_fhandle.c:166:2: error: default label in switch which
covers all enumeration values [-Werror,-Wcovered-switch-default]

* Info 843: Variable 'nruns' (line XXX, file
test/csuite/wt3338_partial_update/main.c) could be declared as const

* src/os_common/os_fhandle.c  XXX  Warning 644: Variable 'file_type_tag'
(line 140) may not have been initialized

* Remove both core.* and *.core when cleaning out the tree.

* src/conn/api_calc_modify.c:154:2: warning: Value stored to 'h' is never read

* Minor logic rewrite to avoid clang-scan complaint:
src/conn/conn_api.c:2618:34: error: this condition has identical
branches [-Werror=duplicated-branches]

* Simplify code paths to avoid clang complaint:
src/utilities/util_list.c:208:17: warning: The left operand of '!=' is
a garbage value
	if (allocsize != 0 && (ret = __wt_block_ckpt_decode(
				    ~~~~~~~~~ ^

* Fix the fix, missing braces.

* Add DWORD, a couple of other known types to the function parsing list.

* include/mutex.i:293:8: warning: macro argument should be enclosed in
parentheses [bugprone-macro-parentheses]

* include/stat.h:268:37: warning: macro argument should be enclosed in
parentheses [bugprone-macro-parentheses]

* WT_FS_OPEN_FILE_TYPE is an enum and the switch exhaustively lists the
cases, but clang, lint and gcc argue over whether or not the switch is
exhaustive, or if a temporary variable inserted into the mix is set but
never read. Break out of the switch, returning some value in all cases,
just to shut everybody up.

* include/mutex.i:293:8: warning: macro argument should be enclosed in
parentheses [bugprone-macro-parentheses]

* Bug, potentially freeing uninitialized memory in an error path.

src/include/buf.i:105:2: warning: The left operand of '!=' is a garbage
value [clang-analyzer-core.UndefinedBinaryOperatorResult]
	__wt_free(session, buf->mem);
	^
src/include/misc.h:119:20: note: expanded from macro '__wt_free'
	if (*(void **)__p != NULL)
	^
conn/conn_stat.c:647:2: note: Calling '__wt_buf_free'
	__wt_buf_free(session, &tmp);

* Avoid clang-tidy garbage value complaint, initialize a variable (that
should be used).

* update

* Update clang, new sets of warnings we're going to have to ignore.

* clang-tidy thinks we can end up using garbage memory for the memcpy,
assert that if the tree is active, there are non-zero chunk counts.

* __wt_atomic_addi64() and  __wt_atomic_subi64() return values.