WT-5999 update format so it's possible for it to restart on an existing database (#5501)
* Rework format to add a -R option that restarts on an existing database.

Split out the checkpoint code into a new file, and start all checkpoints from the operations
code.

* Break out checkpoint code into its own file.

* Break key/value code out into its own file.

* If we're reopening the database we have to reset the row counts.

* Always scan the database before getting angry.

* Changes to support reopening existing databases.

General renaming of underlying objects for consistency; remove Win32 support as part of this
change, we don't run format on Win32 at the moment and some of the existing support was wrong.

Use a timestamp to guarantee backup ID uniqueness, otherwise we fail when we reopen the
database.

Write out a list of the randomly chosen key lengths so we can read it back in on reopen.

* Fix a comment.

* Don't create a local copy of the MAX macro.

* Make naming consistent, "XXXX.copy" everywhere, move naming into local
code so each chunk "owns" name handling.

Give rebalance a simpler structure and let it handle large pathnames.

* Typo fixing, quit using %u for anything other than unsigned int.

* util.c:153:11: error: implicit conversion loses integer precision:
'u_long' (aka 'unsigned long') to 'uint32_t' (aka 'unsigned int')
[-Werror,-Wshorten-64-to-32]

* Fix formatting.

* A few more fixes and a port to the 4.2 branch. Note specifically that "salvage" has to be part
of the check for record gaps, that is, if we salvage, there may be record gaps.

* Don't configure incremental backup in backward compatibility  mode.

* Update .gitignore.

* Fix the backward compatibility test for backup.incremental, "perm" isn't the only check required.

* Fix a typo in a comment.

* Add some explanatory text around the options.