WT-14149 Specify bazel version 7.5.0 when building TCMalloc (#11614)
Since bazel 8.0, they have disabled using the workspace file by default
follow here:
```
WARNING: --enable_bzlmod is set, but no MODULE.bazel file was found at the workspace root. Bazel will create an empty MODULE.bazel file. Please consider migrating your external dependencies from WORKSPACE to MODULE.bazel. For more details, please refer to https://github.com/bazelbuild/bazel/issues/18958.
ERROR: error loading package 'tcmalloc': Unable to find package for @@[unknown repo 'rules_fuzzing' requested from @@]//fuzzing:cc_defs.bzl: The repository '@@[unknown repo 'rules_fuzzing' requested from @@]' could not be resolved: No repository visible as '@rules_fuzzing' from main repository. Was the repository introduced in WORKSPACE? The WORKSPACE file is disabled by default in Bazel 8 (late 2024) and will be removed in Bazel 9 (late 2025), please migrate to Bzlmod. See https://bazel.build/external/migration.
ERROR: /data/wiredtiger/tcmalloc-mongo-SERVER-85737/BUILD:3:18: error loading package 'tcmalloc': Unable to find package for @@[unknown repo 'rules_fuzzing' requested from @@]//fuzzing:cc_defs.bzl: The repository '@@[unknown repo 'rules_fuzzing' requested from @@]' could not be resolved: No repository visible as '@rules_fuzzing' from main repository. Was the repository introduced in WORKSPACE? The WORKSPACE file is disabled by default in Bazel 8 (late 2024) and will be removed in Bazel 9 (late 2025), please migrate to Bzlmod. See https://bazel.build/external/migration. and referenced by '//:libtcmalloc'
ERROR: Analysis of target '//:libtcmalloc' failed; build aborted: Analysis failed
INFO: Elapsed time: 4.636s, Critical Path: 0.03s
INFO: 1 process: 1 internal.
```
To build TCMalloc successfully on a machine, we need to specify the
bazel version.

Also since we now build on bazel 7.1+, I have tested without the sandbox
commands, the FIXME can be removed now. I have verified that the tests
pass within the ticket.