WT-3807 clang static analysis updates (#3842)
* clang static analysis updates

> src/log/log.c:XXX:XXX: warning: Value stored to 'time_start' is never read
>         time_start = time_stop = 0;
>         ^            ~~~~~~~~~~~~~
> src/log/log.c:XXX:XXX: warning: Value stored to 'time_start' is never read
>         time_start = time_stop = 0;
>         ^            ~~~~~~~~~~~~~

* > src/txn/txn_ckpt.c:XXX:XXX: warning: Value stored to 'time_last' is never read
>         time_last = time_start = time_stop = 0;
>         ^           ~~~~~~~~~~~~~~~~~~~~~~~~~~
> src/txn/txn_ckpt.c:XXX:XXX: warning: Value stored to 'time_start' is never read
>         time_start = time_stop = 0;
>         ^            ~~~~~~~~~~~~~

* > src/evict/evict_lru.c:XXX:XXX: warning: Value stored to 'time_now' is never read
>         time_now = time_prev = 0;
>         ^          ~~~~~~~~~~~~~

* > src/session/session_api.c:XXX:XXX: warning: Value stored to 'time_start' is never read
>         time_start = time_stop = 0;
>         ^            ~~~~~~~~~~~~~

* > src/lsm/lsm_tree.c:XXX:XXX: warning: Value stored to 'need_release' is never read
>         need_release = false;
>         ^              ~~~~~

* src/include/btree.i:XXX:XXX: warning: either cast from 'unsigned int' to
'unsigned long' is ineffective, or there is loss of precision before the
conversion [misc-misplaced-widening-cast]

* whitespace

* src/evict/evict_lru.c:743:41: error: variable 'time_prev' may be
uninitialized when used here [-Werror,-Wconditional-uninitialized]

* parenthesize macro usage for clang static analyzer

* Rework the atomic macros to make the clang static analyzer happy.

* warning: different indentation for 'if' and corresponding 'else'
[readability-misleading-indentation]

* wiredtiger.h:3128:5: note: differing parameters are named here:
('session', 'size'), in definition: ('wt_session', 'len')

* warning: function has a definition with different parameter names
[readability-inconsistent-declaration-parameter-name]

* lsm_meta.c:294:5: warning: do not use 'else' after 'continue'
[readability-else-after-return]

Whitespace.

* lsm_cursor.c:1843:3: warning: different indentation for 'if' and
corresponding 'else' [readability-misleading-indentation]

* evict_lru.c:784:5: warning: do not use 'else' after 'break'
[readability-else-after-return]

* conn_reconfig.c:90:4: warning: do not use 'else' after 'return'
[readability-else-after-return]

* wiredtiger.h:2915:5: note: differing parameters are named here:
('errhandler', 'connectionp'), in definition: ('event_handler',
'wt_connp')

* wiredtiger.h:3314:5: warning: function 'wiredtiger_config_validate' has
a definition with different parameter names
[readability-inconsistent-declaration-parameter-name]

* Rework __pack_size() so we return an error in all cases rather than
depending on (size_t -1) to flag an error, and convince the clang
static analyzer there's no path leaving the return size uninitialized.

* Rework __pack_size() so we return an error in all cases rather than
depending on (size_t -1) to flag an error, and convince the clang
static analyzer there's no path leaving the return size uninitialized.

* wiredtiger.h:3128:5: note: differing parameters are named here:
('session', 'size'), in definition: ('wt_session', 'len')
wiredtiger.h:3145:5: note: differing parameters are named here:
('session', 'size'), in definition: ('wt_session', 'len')

* Typo, update the param list as well as the function declaration.

* Update auto-generated files.

* Never ignore __pack_next() failures, consistently use WT_RET_NOTFOUND_OK
to do the check.

* One last pass, be consistent, use "len" for the length of things, and
"size" for the size of buffers.

* Don't return "ret", it's set to WT_NOTFOUND when __pack_next() finishes.

* whitespace

* whitespace

* Review comments: generalize more places that refer to event handling as
exclusively error handling, to refer to more generic message handling.