WT-5255 configuring format with direct I/O support on Evergreen can take an excessive time to run (#5125)
* If direct I/O is configured, turn off external programs, that is, backups, rebalance and salvage.
We can't control how long they take to run, and if the system is under configured, it can take
hours.

* Add a global start time.

Add an timer-expired check function, and rework the main format loop to check if any configured
run-time has expired before doing any actions that are likely to take a long time to run. Assert
we accomplish at least one full set of format work, and if we haven't, fail the run.

Convert the main timer loop to use the library __wt_seconds() function instead of the more
complicated difftime() with time_t types.

Remove the format loop code intended for testing only a bulk-load of the data, that hasn't
been useful for quite a few years.

Add a timer-expired check to the bulk load function because it's the first place that stresses
the I/O subsystem, and we can run forever if the I/O system can't handle the load.

* Simplify value initialization/teardown.

* Fix clang-formatting, long lines allow joining strings.

* Don't pay a function call for a random number once we start doing multithreaded operations,
we make that call a lot.

* Another run at this one: do a basic check in bulk load, if we can't do a bulk load in a minute,
there's just no point, the I/O system can't support the load.

More simplification of the primary work loop, only do a read scan once (after the load), only do
a verify once (at the end), focus more testing time on the workload.

* Use signals to ensure we don't just hang in the library during a rebalance or verify call to
limit our exposure to runs that will trigger Evergreen's timer.

* Windows doesn't support strsignal(3).

* Windows: test\format\t.c(83): error C4100: 'seconds': unreferenced formal parameter

* error: ISO C90 forbids mixed declarations and code [-Werror=declaration-after-statement]

* Exit EXIT_FAILURE when direct I/O configurations time out.

Minor messaging clean up and clarification.

* Fix sort problem in format.sh usage statement.

* Revert "Fix sort problem in format.sh usage statement."

This reverts commit 18e2d5a08625e2f7c6aca8fc6a1c85bf77c7b775.