WT-18351 Flaky test_checkpoint_scrub_evict.py on Windows (#14468)
We are seeing an intermittent assertion error in
test_scrub_stat_after_checkpoint:
AssertionError: 0 not greater than 0 : cache_write_restore_scrub should
increase after a precise checkpoint: before=0, after=0

The precise checkpoint scenarios asserted that cache_write_restore_scrub
increases after a checkpoint, but left scrub eviction setting on auto
with an intentionally small cache. The test can fail in scenarios where
cache pressure would turn scrub eviction off. This fix explicitly sets
precise checkpoint scrub eviction on. It leaves the fuzzy checkpoint on
auto so the "must be zero" assertions for fuzzy checkpoint isn't
trivially passing.

test_checkpoint_scrub_evict_config also in this test file asserts the
different on, off, and auto configs so we can leave the rest of the test
with scrub turned on. [Stress test patch build
here,](https://spruce.corp.mongodb.com/version/6a8529b0b633b90007e5ca3f/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC)
no error after 280 iterations.