Fix debug display of the HS cursor when pointing to a modify record: we don't need to allocate a WT_UPDATE structure, just convert the underlying function to take a data pointer. This fixes a typing problem in the call to allocate the WT_UPDATE structure:
bt_debug.c:437:54: error: implicit conversion loses integer precision: 'uint64_t' (aka 'unsigned
long') to 'u_int' (aka 'unsigned int') [-Werror,-Wshorten-64-to-32]