WT-4421 Add a way to calculate modify operations. (#4353)
* Remove dumb implementation.

* Revert a change for doxygen 1.8.14.

* ../../../examples/c/ex_all.c:1361:15: error: variable length array used [-Werror,-Wvla]

* Include size changes in calculated offsets.

* Fix spurious "maybe-uninitialized" warnings.

* Add back in the bounds check on p1.

* Simplification.

* Don't scan back into already-used bytes.

Add a session parameter for assertions, logging and potentially
statistics.

* API change to wiredtiger.in.

* Initialze "used" fields before searching for a prefix match.

* Bug fix: if there is a matching prefix, start scanning after it.

Also reorder static functions alphabetically.

* Add a Python API for wiredtiger_calc_modify, fix an off-by-one bug.

* Avoid C99-ism.

* Add a test case for wiredtiger_calc_modify.

* Review feedback, minor cleanup, improved docs.

* Further minor simplification: no functional change.

(cherry picked from commit 4e2c76044bca5d51f49abed9b43aac078cf302d3)